name: Jana Kellam
favicon: null
layout_spectrum: 0.9635849369224161
typography_spectrum: 0.550776188261807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5759231899864972
  lightness: 0.853458110941574
  saturation: 0.9446916696615517
  rhythmicContrast: 0.9394096035975963
purpose: []
